#!/usr/bin/env python3
"""
Generate pre-computed RGB→Spectra6 color lookup table at build time.

This eliminates the ~150ms runtime LUT generation cost by computing
the entire 32KB table during compilation.

The LUT uses Lab color space for perceptually accurate color matching,
identical to the runtime algorithm.

Usage:
    python generate_color_lut.py > ../lib/EL133UF1/EL133UF1_ColorLUT.h
    
Or via PlatformIO pre-build script (see platformio.ini)
"""

import math
import sys
import os

# LUT configuration - must match EL133UF1_Color.h
COLOR_LUT_BITS = 5
COLOR_LUT_SIZE = 1 << COLOR_LUT_BITS  # 32
COLOR_LUT_SHIFT = 8 - COLOR_LUT_BITS   # 3

# Spectra 6 color codes (must match EL133UF1.h)
EL133UF1_BLACK = 0
EL133UF1_WHITE = 1
EL133UF1_YELLOW = 2
EL133UF1_RED = 3
EL133UF1_BLUE = 5
EL133UF1_GREEN = 6

SPECTRA_CODE = [
    EL133UF1_BLACK,
    EL133UF1_WHITE,
    EL133UF1_YELLOW,
    EL133UF1_RED,
    EL133UF1_BLUE,
    EL133UF1_GREEN
]

# Default calibrated Spectra 6 palette (RGB values)
# Must match useDefaultPalette() in EL133UF1_Color.cpp
DEFAULT_PALETTE = [
    (10, 10, 10),       # Black
    (245, 245, 235),    # White (slightly warm)
    (245, 210, 50),     # Yellow
    (190, 60, 55),      # Red (brick/tomato)
    (45, 75, 160),      # Blue (navy)
    (55, 140, 85),      # Green (teal/forest)
]

# Pre-computed sRGB to linear LUT
srgb_to_linear = []
for i in range(256):
    v = i / 255.0
    if v > 0.04045:
        srgb_to_linear.append(((v + 0.055) / 1.055) ** 2.4)
    else:
        srgb_to_linear.append(v / 12.92)


def rgb_to_lab(r, g, b):
    """Convert RGB to CIE Lab color space."""
    # sRGB to linear RGB
    rf = srgb_to_linear[r]
    gf = srgb_to_linear[g]
    bf = srgb_to_linear[b]
    
    # Linear RGB to XYZ
    x = rf * 0.4124564 + gf * 0.3575761 + bf * 0.1804375
    y = rf * 0.2126729 + gf * 0.7151522 + bf * 0.0721750
    z = rf * 0.0193339 + gf * 0.1191920 + bf * 0.9503041
    
    # Normalize for D65 white point
    x /= 0.95047
    y /= 1.00000
    z /= 1.08883
    
    # XYZ to Lab
    epsilon = 0.008856
    kappa = 903.3
    
    fx = x ** (1/3) if x > epsilon else (kappa * x + 16.0) / 116.0
    fy = y ** (1/3) if y > epsilon else (kappa * y + 16.0) / 116.0
    fz = z ** (1/3) if z > epsilon else (kappa * z + 16.0) / 116.0
    
    L = 116.0 * fy - 16.0
    a = 500.0 * (fx - fy)
    lab_b = 200.0 * (fy - fz)
    
    return (L, a, lab_b)


def find_nearest_lab(r, g, b, palette_lab):
    """Find nearest palette color using Lab color space."""
    L, a, lab_b = rgb_to_lab(r, g, b)
    
    min_dist = float('inf')
    best_idx = 1  # Default to white
    
    for i, (pL, pa, pb) in enumerate(palette_lab):
        # CIE76 Delta E (Euclidean distance in Lab space)
        dL = L - pL
        da = a - pa
        db = lab_b - pb
        dist = dL * dL + da * da + db * db
        
        if dist < min_dist:
            min_dist = dist
            best_idx = i
    
    return SPECTRA_CODE[best_idx]


def generate_lut(palette):
    """Generate the complete RGB→Spectra LUT."""
    # Pre-compute Lab values for palette
    palette_lab = [rgb_to_lab(r, g, b) for r, g, b in palette]
    
    lut = []
    total = COLOR_LUT_SIZE ** 3
    
    for ri in range(COLOR_LUT_SIZE):
        # Expand 5-bit to 8-bit with proper rounding
        r = (ri << COLOR_LUT_SHIFT) | (ri >> (COLOR_LUT_BITS - COLOR_LUT_SHIFT))
        for gi in range(COLOR_LUT_SIZE):
            g = (gi << COLOR_LUT_SHIFT) | (gi >> (COLOR_LUT_BITS - COLOR_LUT_SHIFT))
            for bi in range(COLOR_LUT_SIZE):
                b = (bi << COLOR_LUT_SHIFT) | (bi >> (COLOR_LUT_BITS - COLOR_LUT_SHIFT))
                color = find_nearest_lab(r, g, b, palette_lab)
                lut.append(color)
    
    return lut


def format_lut_as_c_header(lut):
    """Format LUT as a C header file."""
    lines = []
    lines.append("/**")
    lines.append(" * @file EL133UF1_ColorLUT.h")
    lines.append(" * @brief Pre-computed RGB→Spectra6 color lookup table")
    lines.append(" * ")
    lines.append(" * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY")
    lines.append(" * Generated by: scripts/generate_color_lut.py")
    lines.append(" * ")
    lines.append(" * This LUT maps 5-bit-per-channel RGB values to Spectra 6 colors")
    lines.append(" * using CIE Lab perceptual color matching.")
    lines.append(" * ")
    lines.append(f" * Size: {len(lut)} bytes ({COLOR_LUT_SIZE}x{COLOR_LUT_SIZE}x{COLOR_LUT_SIZE})")
    lines.append(" */")
    lines.append("")
    lines.append("#ifndef EL133UF1_COLORLUT_H")
    lines.append("#define EL133UF1_COLORLUT_H")
    lines.append("")
    lines.append("#include <Arduino.h>")
    lines.append("")
    lines.append("// Store in flash (PROGMEM) to save RAM")
    lines.append(f"static const uint8_t PROGMEM SPECTRA6_COLOR_LUT[{len(lut)}] = {{")
    
    # Format data in rows of 32 values
    for i in range(0, len(lut), 32):
        chunk = lut[i:i+32]
        line = "    " + ", ".join(f"{v}" for v in chunk) + ","
        lines.append(line)
    
    lines.append("};")
    lines.append("")
    lines.append("#endif // EL133UF1_COLORLUT_H")
    
    return "\n".join(lines)


def main():
    # Generate LUT with default palette
    print(f"Generating {COLOR_LUT_SIZE}x{COLOR_LUT_SIZE}x{COLOR_LUT_SIZE} color LUT...", file=sys.stderr)
    lut = generate_lut(DEFAULT_PALETTE)
    print(f"Generated {len(lut)} entries", file=sys.stderr)
    
    # Output as C header
    header = format_lut_as_c_header(lut)
    
    # Write to file or stdout
    if len(sys.argv) > 1:
        output_path = sys.argv[1]
        with open(output_path, 'w') as f:
            f.write(header)
        print(f"Written to {output_path}", file=sys.stderr)
    else:
        print(header)


if __name__ == "__main__":
    main()
