#!/usr/bin/env python3
"""
Generate C++ header file from web assets (HTML/CSS/JS files).

This script reads web files and generates a header file with the content
embedded as const char* strings, similar to generate_cert_header.py.

Usage: Called automatically by PlatformIO pre-build script
"""

import os
import sys

def generate_web_header(source, target, env):
    """Generate web assets header file from web/ directory."""
    
    project_dir = env.subst("$PROJECT_DIR")
    web_dir = os.path.join(project_dir, "web")
    header_file = os.path.join(project_dir, "src", "web_assets.h")
    
    # Ensure web directory exists
    if not os.path.exists(web_dir):
        print(f"ERROR: web directory does not exist: {web_dir}")
        sys.exit(1)
    
    # Read HTML file - must exist, no fallback
    html_file = os.path.join(web_dir, "index.html")
    if not os.path.exists(html_file):
        print(f"ERROR: web/index.html not found at {html_file}")
        print("  The WiFi web interface HTML file is required for the build.")
        sys.exit(1)
    
    print(f"Reading HTML file: {html_file}")
    try:
        with open(html_file, 'r', encoding='utf-8') as f:
            html_content = f.read()
        print(f"  Read {len(html_content)} bytes from {html_file}")
    except IOError as e:
        print(f"ERROR: Failed to read {html_file}: {e}")
        sys.exit(1)
    
    # Generate hour checkboxes HTML (24 hours)
    hour_checkboxes = ""
    for i in range(24):
        hour_checkboxes += f"<label style='display:flex;align-items:center;gap:5px;cursor:pointer;'><input type='checkbox' class='hourCheckbox' data-hour='{i}' style='cursor:pointer;'>{i:02d}:00</label>"
    
    # Replace placeholder with generated checkboxes
    html_content = html_content.replace("<div style=\"display:flex;flex-wrap:wrap;gap:10px;margin:10px 0;padding:10px;background:#f9f9f9;border-radius:4px;\" id=\"hourSchedule\"></div>",
                                        f"<div style=\"display:flex;flex-wrap:wrap;gap:10px;margin:10px 0;padding:10px;background:#f9f9f9;border-radius:4px;\">{hour_checkboxes}</div>")
    
    # Generate header file
    header_content = f"""// Web Assets (HTML/CSS/JS)
// 
// Auto-generated by scripts/generate_web_header.py
// Source files in web/ directory
//
// This file contains the embedded HTML content for the management interface.
// Edit web/index.html and rebuild to update.

#ifndef WEB_ASSETS_H
#define WEB_ASSETS_H

// Embedded HTML content (from web/index.html)
const char* WEB_HTML_CONTENT = R"HTML(
{html_content}
)HTML";

// Length of HTML content (for reference, not needed for null-terminated string)
const size_t WEB_HTML_CONTENT_LEN = {len(html_content)};

#endif // WEB_ASSETS_H
"""
    
    # Write header file
    print(f"Writing header file: {header_file}")
    try:
        with open(header_file, 'w', encoding='utf-8') as f:
            f.write(header_content)
        print(f"✓ Web assets header generated: {header_file}")
        print(f"  HTML content size: {len(html_content)} bytes")
        print(f"  Header file size: {len(header_content)} bytes")
    except IOError as e:
        print(f"ERROR: Failed to write header file: {e}")
        sys.exit(1)

# Register the function to run before building (only when called from PlatformIO)
# Use "buildprog" instead of file-specific target to ensure it runs every build
try:
    Import("env")
    env.AddPreAction("buildprog", generate_web_header)
except:
    # Called directly (for testing) - run the function manually
    import os
    class FakeEnv:
        def subst(self, s):
            return os.path.dirname(os.path.dirname(__file__))
    fake_env = FakeEnv()
    generate_web_header(None, None, fake_env)

