#!/usr/bin/env python3
"""
Generate C++ header file from web assets (HTML/CSS/JS files) - Standalone version.

This script reads web files and generates a header file with the content
embedded as const char* strings.

Usage:
    python3 scripts/generate_web_header_standalone.py [project_dir]
    
    If project_dir is not specified, uses the current working directory.
    The script expects:
    - web/index.html to exist (source file)
    - src/web_assets.h to be created (output file)
"""

import os
import sys
import argparse

def generate_web_header(project_dir=None):
    """Generate web assets header file from web/ directory."""
    
    # Use current directory if project_dir not specified
    if project_dir is None:
        project_dir = os.getcwd()
    
    # Convert to absolute path
    project_dir = os.path.abspath(project_dir)
    
    web_dir = os.path.join(project_dir, "web")
    header_file = os.path.join(project_dir, "src", "web_assets.h")
    
    print(f"Project directory: {project_dir}")
    print(f"Web directory: {web_dir}")
    print(f"Header file: {header_file}")
    print()
    
    # Ensure web directory exists
    if not os.path.exists(web_dir):
        print(f"ERROR: web directory does not exist: {web_dir}")
        sys.exit(1)
    
    # Read HTML file - must exist, no fallback
    html_file = os.path.join(web_dir, "index.html")
    if not os.path.exists(html_file):
        print(f"ERROR: web/index.html not found at {html_file}")
        print("  The WiFi web interface HTML file is required.")
        sys.exit(1)
    
    print(f"Reading HTML file: {html_file}")
    try:
        with open(html_file, 'r', encoding='utf-8') as f:
            html_content = f.read()
        print(f"  Read {len(html_content)} bytes from {html_file}")
    except IOError as e:
        print(f"ERROR: Failed to read {html_file}: {e}")
        sys.exit(1)
    
    # Generate hour checkboxes HTML (24 hours)
    hour_checkboxes = ""
    for i in range(24):
        hour_checkboxes += f"<label style='display:flex;align-items:center;gap:5px;cursor:pointer;'><input type='checkbox' class='hourCheckbox' data-hour='{i}' style='cursor:pointer;'>{i:02d}:00</label>"
    
    # Replace placeholder with generated checkboxes
    # Note: The placeholder might not exist in the HTML, so we check first
    placeholder = "<div style=\"display:flex;flex-wrap:wrap;gap:10px;margin:10px 0;padding:10px;background:#f9f9f9;border-radius:4px;\" id=\"hourSchedule\"></div>"
    replacement = f"<div style=\"display:flex;flex-wrap:wrap;gap:10px;margin:10px 0;padding:10px;background:#f9f9f9;border-radius:4px;\">{hour_checkboxes}</div>"
    
    if placeholder in html_content:
        html_content = html_content.replace(placeholder, replacement)
        print("  ✓ Replaced hour schedule placeholder with generated checkboxes")
    else:
        # Try alternative placeholder (with dark theme background)
        alt_placeholder = "<div style=\"display:flex;flex-wrap:wrap;gap:10px;margin:10px 0;padding:10px;background:#1a1a1a;border-radius:4px;\" id=\"hourSchedule\"></div>"
        alt_replacement = f"<div style=\"display:flex;flex-wrap:wrap;gap:10px;margin:10px 0;padding:10px;background:#1a1a1a;border-radius:4px;\">{hour_checkboxes}</div>"
        if alt_placeholder in html_content:
            html_content = html_content.replace(alt_placeholder, alt_replacement)
            print("  ✓ Replaced hour schedule placeholder (dark theme) with generated checkboxes")
        else:
            print("  ⚠ WARNING: Hour schedule placeholder not found in HTML (checkboxes not generated)")
    
    # Generate header file
    header_content = f"""// Web Assets (HTML/CSS/JS)
// 
// Auto-generated by scripts/generate_web_header.py (standalone version)
// Source files in web/ directory
//
// This file contains the embedded HTML content for the management interface.
// Edit web/index.html and rebuild to update.

#ifndef WEB_ASSETS_H
#define WEB_ASSETS_H

// Embedded HTML content (from web/index.html)
const char* WEB_HTML_CONTENT = R"HTML(
{html_content}
)HTML";

// Length of HTML content (for reference, not needed for null-terminated string)
const size_t WEB_HTML_CONTENT_LEN = {len(html_content)};

#endif // WEB_ASSETS_H
"""
    
    # Ensure src directory exists
    src_dir = os.path.dirname(header_file)
    if not os.path.exists(src_dir):
        print(f"Creating src directory: {src_dir}")
        os.makedirs(src_dir, exist_ok=True)
    
    # Write header file
    print(f"Writing header file: {header_file}")
    try:
        with open(header_file, 'w', encoding='utf-8') as f:
            f.write(header_content)
        print(f"✓ Web assets header generated: {header_file}")
        print(f"  HTML content size: {len(html_content)} bytes")
        print(f"  Header file size: {len(header_content)} bytes")
    except IOError as e:
        print(f"ERROR: Failed to write header file: {e}")
        sys.exit(1)
    
    print()
    print("✓ Success!")

def main():
    """Main entry point for standalone script."""
    parser = argparse.ArgumentParser(
        description='Generate C++ header file from web assets',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
    # Run from project root
    python3 scripts/generate_web_header_standalone.py
    
    # Specify project directory
    python3 scripts/generate_web_header_standalone.py /path/to/project
        """
    )
    parser.add_argument(
        'project_dir',
        nargs='?',
        default=None,
        help='Project directory (default: current working directory)'
    )
    
    args = parser.parse_args()
    
    try:
        generate_web_header(args.project_dir)
    except KeyboardInterrupt:
        print("\n\nInterrupted by user")
        sys.exit(1)
    except Exception as e:
        print(f"\nERROR: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)

if __name__ == "__main__":
    main()
