#!/usr/bin/env python3
"""
Generate certificates.h header file from PEM certificate files.

This script:
1. Checks if certificates/server_cert.pem and certificates/server_key.pem exist
2. If not, generates them using openssl
3. Converts the PEM files to C header format with const char arrays
4. Writes src/certificates.h

This is a PlatformIO pre-build script that runs before compilation.
"""

Import("env")
import os
import subprocess
import sys
    
def ensure_certificates_exist(cert_dir):
    """Ensure certificate PEM files exist, generate if needed."""
    cert_file = os.path.join(cert_dir, "server_cert.pem")
    key_file = os.path.join(cert_dir, "server_key.pem")
    
    # Check if both files exist and are valid
    need_generate = False
    if not os.path.exists(cert_file) or not os.path.exists(key_file):
        need_generate = True
        print("Certificate files not found, generating...")
    else:
        # Verify files are not empty and contain valid PEM data
        try:
            with open(cert_file, 'r') as f:
                cert_content = f.read()
                if not cert_content.strip() or 'BEGIN CERTIFICATE' not in cert_content:
                    need_generate = True
                    print("Certificate file is invalid, regenerating...")
            
            with open(key_file, 'r') as f:
                key_content = f.read()
                if not key_content.strip() or ('BEGIN PRIVATE KEY' not in key_content and 'BEGIN RSA PRIVATE KEY' not in key_content):
                    need_generate = True
                    print("Key file is invalid, regenerating...")
        except Exception as e:
            print(f"Error checking certificate files: {e}, regenerating...")
            need_generate = True
    
    if need_generate:
        # Ensure certificates directory exists
        os.makedirs(cert_dir, exist_ok=True)
        
        # Generate private key
        print("Generating 2048-bit RSA private key...")
        try:
            subprocess.run(
                ["openssl", "genrsa", "-out", key_file, "2048"],
                check=True,
                capture_output=True
            )
            print("Private key generated successfully")
        except subprocess.CalledProcessError as e:
            print(f"ERROR: Failed to generate private key: {e.stderr.decode()}")
            return False
        except FileNotFoundError:
            print("ERROR: openssl not found. Please install OpenSSL.")
            return False
    
        # Generate self-signed certificate (valid for 10 years)
        print("Generating self-signed certificate...")
        try:
            subprocess.run(
                ["openssl", "req", "-new", "-x509", "-key", key_file, 
                "-out", cert_file, "-days", "3650",
                 "-subj", "/C=US/ST=State/L=City/O=ESP32-P4/CN=esp32.local"],
                check=True,
                capture_output=True
            )
            print("Certificate generated successfully")
        except subprocess.CalledProcessError as e:
            print(f"ERROR: Failed to generate certificate: {e.stderr.decode()}")
            return False
    
    return True

def pem_to_c_string(pem_content):
    """Convert PEM content to C string format, preserving full PEM structure."""
    # Keep the full PEM content but escape it for C string
    # Replace newlines with \n and escape quotes
    pem_escaped = pem_content.replace('\\', '\\\\').replace('"', '\\"').replace('\n', '\\n')
    return pem_escaped

def generate_cert_header(cert_file, key_file, output_file):
    """Generate certificates.h from PEM files."""
    try:
        # Read certificate
        with open(cert_file, 'r') as f:
            cert_pem = f.read()
        
        # Read private key
        with open(key_file, 'r') as f:
            key_pem = f.read()
        
        # Convert to C strings
        cert_data = pem_to_c_string(cert_pem)
        key_data = pem_to_c_string(key_pem)
    
    # Generate header file
        header_content = f"""/**
 * @file certificates.h
 * @brief SSL/TLS certificates for ESP32-P4 HTTPS server
 * 
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by: scripts/generate_cert_header.py
 * 
 * This file contains self-signed certificate and private key
 * for the HTTPS server. These are embedded as const char arrays
 * in full PEM format.
 */

#ifndef CERTIFICATES_H
#define CERTIFICATES_H

// Server certificate (full PEM format)
static const char server_cert_pem[] = "{cert_data}";

// Server private key (full PEM format)
static const char server_key_pem[] = "{key_data}";

// Aliases for compatibility with code that uses server_cert/server_key
#define server_cert server_cert_pem
#define server_key server_key_pem

#endif // CERTIFICATES_H
"""
    
    # Write header file
        output_dir = os.path.dirname(output_file)
        if output_dir and not os.path.exists(output_dir):
            os.makedirs(output_dir, exist_ok=True)
        
        with open(output_file, 'w') as f:
            f.write(header_content)
        
        print(f"Generated {output_file} successfully")
        return True
        
    except Exception as e:
        print(f"ERROR: Failed to generate certificate header: {e}")
        return False

def generate_certificates(source, target, env):
    """PlatformIO pre-build action to generate certificates.h."""
    project_dir = env.subst("$PROJECT_DIR")
    cert_dir = os.path.join(project_dir, "certificates")
    cert_file = os.path.join(cert_dir, "server_cert.pem")
    key_file = os.path.join(cert_dir, "server_key.pem")
    output_file = os.path.join(project_dir, "src", "certificates.h")
    
    # Ensure certificates exist
    if not ensure_certificates_exist(cert_dir):
        print("ERROR: Failed to ensure certificates exist")
        return
    
    # Generate header file
    if not generate_cert_header(cert_file, key_file, output_file):
        print("ERROR: Failed to generate certificate header")
        return
    
    print("Certificate generation completed successfully")

# Register the pre-build action
env.AddPreAction("buildprog", generate_certificates)
