// Stub certificates.h file
// This file is normally generated by scripts/generate_cert_header.py
// If you need SSL support, run the pre-build script or generate certificates manually

#ifndef CERTIFICATES_H
#define CERTIFICATES_H

// Placeholder certificate and key (self-signed, for development only)
// Replace with your own certificates for production use
const char server_cert[] = 
"-----BEGIN CERTIFICATE-----\n"
"MIIDXTCCAkWgAwIBAgIJAKL3MCP+ja4gMA0GCSqGSIb3DQEBCQUAMEUxCzAJBgNV\n"
"BAYTAkFVMRMwEQYDVQQIDApTb21lLVN0YXRlMSEwHwYDVQQKDBhJbnRlcm5ldCBX\n"
"aWRnaXRzIFB0eSBMdGQwHhcNMjAwMTAxMDAwMDAwWhcNMzAwMTAxMDAwMDAwWjBF\n"
"MQswCQYDVQQGEwJBVTETMBEGA1UECAwKU29tZS1TdGF0ZTEhMB8GA1UECgwYSW50\n"
"ZXJuZXQgV2lkZ2l0cyBQdHkgTHRkMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIB\n"
"CgKCAQEAyMEdY1flRVLCLSc5hzU1rrhfx3WiBHLdH9mSeA8aUayMq6lmewzYh6Ta\n"
"M7aSG1uLADTOoyJLtqT3W1T3K8XvO6F0R8qdvJe6e7Kv2jx5D+u6d+n3Yjm8b+mX\n"
"2QYhFyZQmlHsZ2d4gUz6YwGX/Eu5hSi6HuQRXtAhowHDNURb0YbCaK6D6cErrpf7\n"
"D+GFnC+3nddtJ5x+6L7l5BweA6yymzO8wLzGjNt7B2a3J3J3J3J3J3J3J3J3J3J3\n"
"J3J3J3J3J3J3J3J3J3J3J3J3J3J3J3J3J3J3J3J3J3J3J3J3J3J3J3J3J3J3J3J3\n"
"J3J3J3J3J3J3J3J3J3J3J3J3J3J3J3J3J3J3J3J3J3J3J3J3J3J3J3J3J3J3J3J3\n"
"J3J3J3J3J3J3J3J3J3J3J3J3J3J3J3J3J3J3J3J3J3J3J3J3J3J3J3J3J3J3J3J3\n"
"J3J3J3J3J3J3J3J3J3J3J3J3J3J3J3J3J3J3J3J3J3J3J3J3J3J3J3J3J3J3J3J3\n"
"-----END CERTIFICATE-----\n";

const char server_key[] = 
"-----BEGIN PRIVATE KEY-----\n"
"MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDIwR1jV+VFUstJ\n"
"zmHNTVuuF/HdaIEct0f2ZJ4DxpRrIyrqWZ7DNiHpNowtpoZW4sANM6jIku2pPdbV\n"
"Pcrxe87oXRHyr28l7p7sq/aPHkP67p36fdiObxv6ZfZBiEXJlCaUexnZ3iBTPpjA\n"
"Zf8S7mFKLoe5BFe0CGjAcM1RFvRhsJoroPpwSul9/sP4YWcL7ed123nHH7ovuXk\n"
"HB4DrLKbM7zAvMaM23sHZrcncncncncncncncncncncncncncncncncncncncncn\n"
"cncncncncncncncncncncncncncncncncncncncncncncncncncncncncncncncncn\n"
"cncncncncncncncncncncncncncncncncncncncncncncncncncncncncncncncncn\n"
"cncncncncncncncncncncncncncncncncncncncncncncncncncncncncncncncncn\n"
"-----END PRIVATE KEY-----\n";

#endif // CERTIFICATES_H

